"""rename department

Revision ID: 26fce59c2b2f
Revises: e322f7ffbfef
Create Date: 2024-10-16 15:12:26.413540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fce59c2b2f'
down_revision = 'e322f7ffbfef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
